const { NIVEIS_ACESSO } = require("../../../domain/value-objects/niveis-acesso");

const usuariosSeed = [
  {
    id: 1,
    nome: "Ana Paula Souza",
    email: "paciente@teste.com",
    senha: "123456",
    nivel_acesso: NIVEIS_ACESSO.PACIENTE,
    clinica_id: null,
    status: "ativo",
  },
  {
    id: 2,
    nome: "Admin Clinica",
    email: "admin@teste.com",
    senha: "123456",
    nivel_acesso: NIVEIS_ACESSO.ADMIN_CLINICA,
    clinica_id: 1,
    status: "ativo",
  },
  {
    id: 3,
    nome: "Admin Master",
    email: "master@teste.com",
    senha: "123456",
    nivel_acesso: NIVEIS_ACESSO.ADMIN_MASTER,
    clinica_id: null,
    status: "ativo",
  },
  {
    id: 4,
    nome: "Roberto Lima",
    email: "medico@teste.com",
    senha: "123456",
    nivel_acesso: NIVEIS_ACESSO.MEDICO,
    clinica_id: 1,
    status: "ativo",
  },
];

const clinicasSeed = [
  {
    id: 1,
    nome: "UBS Bacaxa",
    bairro: "Bacaxa",
    endereco: "Rua Principal, 100 - Bacaxa, Saquarema/RJ",
    telefone: "(22) 2651-0001",
    especialidades: ["Clinica Geral", "Pediatria", "Vacinacao"],
    especialidadesExames: ["Hemograma completo", "Glicemia em jejum", "Urina tipo 1"],
    aberta: true,
    status: "ativa",
    responsavel: "Dra. Helena Martins",
    capacidadeDiaria: 96,
    atendimentosMes: 1284,
    satisfacao: 94,
    horario: "Seg a Sex: 07h as 17h",
    emoji: "+",
    latitude: -22.9169,
    longitude: -42.6169,
  },
  {
    id: 2,
    nome: "UBS Itauna",
    bairro: "Itauna",
    endereco: "Av. Oceanica, 250 - Itauna, Saquarema/RJ",
    telefone: "(22) 2651-0002",
    especialidades: ["Clinica Geral", "Ginecologia", "Pre-Natal"],
    especialidadesExames: ["Colesterol total e fracoes", "Ultrassonografia", "Preventivo"],
    aberta: true,
    status: "ativa",
    responsavel: "Dr. Ricardo Azevedo",
    capacidadeDiaria: 74,
    atendimentosMes: 986,
    satisfacao: 91,
    horario: "Seg a Sex: 08h as 16h",
    emoji: "+",
    latitude: -22.9338,
    longitude: -42.4939,
  },
  {
    id: 3,
    nome: "UBS Vilatur",
    bairro: "Vilatur",
    endereco: "Rua das Flores, 45 - Vilatur, Saquarema/RJ",
    telefone: "(22) 2651-0003",
    especialidades: ["Clinica Geral", "Odontologia"],
    especialidadesExames: ["Raio-X", "Hemograma completo"],
    aberta: false,
    status: "temporariamente_fechada",
    responsavel: "Enf. Marcos Vieira",
    capacidadeDiaria: 42,
    atendimentosMes: 236,
    satisfacao: 86,
    horario: "Temporariamente fechada",
    emoji: "+",
    latitude: -22.9344,
    longitude: -42.6835,
  },
  {
    id: 4,
    nome: "UBS Sampaio Correa",
    bairro: "Sampaio Correa",
    endereco: "Estrada Municipal, 78 - Sampaio Correa, Saquarema/RJ",
    telefone: "(22) 2651-0004",
    especialidades: ["Clinica Geral", "Pediatria", "Nutricao"],
    especialidadesExames: ["Hemograma completo", "Glicemia em jejum", "Colesterol total e fracoes"],
    aberta: true,
    status: "ativa",
    responsavel: "Dra. Priscila Rocha",
    capacidadeDiaria: 88,
    atendimentosMes: 1108,
    satisfacao: 93,
    horario: "Seg a Sex: 07h as 17h",
    emoji: "+",
    latitude: -22.8747,
    longitude: -42.6594,
  },
];

const consultasSeed = [
  {
    id: 101,
    data: "2026-04-19",
    horario: "08:00",
    clinica_id: 1,
    paciente_id: 1,
    paciente: "Ana Paula Souza",
    medico_id: 110,
    medico: "Dr. Roberto Lima",
    especialidade: "Clinica Geral",
    status: "realizada",
  },
  {
    id: 102,
    data: "2026-04-19",
    horario: "08:30",
    clinica_id: 1,
    paciente_id: 7,
    paciente: "Luciana Freitas",
    medico_id: 110,
    medico: "Dr. Roberto Lima",
    especialidade: "Pediatria",
    status: "confirmada",
  },
  {
    id: 103,
    data: "2026-04-19",
    horario: "09:00",
    clinica_id: 2,
    paciente_id: 8,
    paciente: "Camila Pires",
    medico_id: 120,
    medico: "Dra. Beatriz Nunes",
    especialidade: "Ginecologia",
    status: "agendada",
  },
  {
    id: 104,
    data: "2026-04-18",
    horario: "10:00",
    clinica_id: 2,
    paciente_id: 1,
    paciente: "Ana Paula Souza",
    medico_id: 120,
    medico: "Dra. Beatriz Nunes",
    especialidade: "Pre-Natal",
    status: "confirmada",
  },
  {
    id: 105,
    data: "2026-04-18",
    horario: "11:00",
    clinica_id: 1,
    paciente_id: 9,
    paciente: "Andre Oliveira",
    medico_id: 110,
    medico: "Dr. Roberto Lima",
    especialidade: "Clinica Geral",
    status: "cancelada",
  },
];

module.exports = { usuariosSeed, clinicasSeed, consultasSeed };
